version: "3.9"
services:
  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=shortcut
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  app:
    image: 'car-directory:latest'
    container_name: car-directory
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shortcut
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8080:8080
    depends_on:
      - db